/**
 *
 * @author Santiago López
 */

public class Purchase_order extends javax.swing.JFrame {

    /**
     * Creates new form EV02
     */
    public Purchase_order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNmrslt = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jValue1 = new javax.swing.JTextField();
        jValue2 = new javax.swing.JTextField();
        jValue3 = new javax.swing.JTextField();
        jQty1 = new javax.swing.JTextField();
        jQty2 = new javax.swing.JTextField();
        jQty3 = new javax.swing.JTextField();
        jTotal = new javax.swing.JTextField();
        jTotal1 = new javax.swing.JTextField();
        jTotal2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTotal3 = new javax.swing.JTextField();
        calcBtn = new javax.swing.JButton();

        jTextField7.setText("jTextField1");

        jTextField8.setText("jTextField1");

        jTextField9.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Purchase Order (PO)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Client:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 66, -1, -1));

        nameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFldActionPerformed(evt);
            }
        });
        getContentPane().add(nameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Unit Value");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Total Value");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jNmrslt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jNmrslt.setText("Dear _, the total of your order is: ");
        getContentPane().add(jNmrslt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 98, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 98, -1));
        getContentPane().add(jValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, -1));
        getContentPane().add(jValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, -1));
        getContentPane().add(jValue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, -1));
        getContentPane().add(jQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 70, -1));
        getContentPane().add(jQty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 70, -1));
        getContentPane().add(jQty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 70, -1));

        jTotal.setEditable(false);
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 284, 120, 30));

        jTotal1.setEditable(false);
        jTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotal1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 120, -1));

        jTotal2.setEditable(false);
        getContentPane().add(jTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 120, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Total Value");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jTotal3.setEditable(false);
        getContentPane().add(jTotal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 120, -1));

        calcBtn.setText("CALCULATE");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });
        getContentPane().add(calcBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFldActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
                
    }//GEN-LAST:event_jTotalActionPerformed

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        
        int value1 = Integer.parseInt(jValue1.getText());
        int value2 = Integer.parseInt(jValue2.getText());
        int value3 = Integer.parseInt(jValue3.getText());
        
        int qty1 = Integer.parseInt(jQty1.getText());
        int qty2 = Integer.parseInt(jQty2.getText());
        int qty3 = Integer.parseInt(jQty3.getText());
        
        int total1 = value1*qty1;
        int total2 = value2*qty2;
        int total3 = value3*qty3;
        
        jTotal1.setText("$"+total1);
        jTotal2.setText("$"+total2);
        jTotal3.setText("$"+total3);
        
        int total = total1+total2+total3;
        jTotal.setText("$"+total);
        
        String name = nameFld.getText();
        jNmrslt.setText("Dear " + name + ", the total of your purchase is: $" + total);
    }//GEN-LAST:event_calcBtnActionPerformed

    private void jTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jNmrslt;
    private javax.swing.JTextField jQty1;
    private javax.swing.JTextField jQty2;
    private javax.swing.JTextField jQty3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTotal;
    private javax.swing.JTextField jTotal1;
    private javax.swing.JTextField jTotal2;
    private javax.swing.JTextField jTotal3;
    private javax.swing.JTextField jValue1;
    private javax.swing.JTextField jValue2;
    private javax.swing.JTextField jValue3;
    private javax.swing.JTextField nameFld;
    // End of variables declaration//GEN-END:variables
}
